Entity/MetaClass.php
<?php

namespace Logicamente\DocumentorBundle\Entity;

use ArrayIterator;
use ReflectionClass;

/**
 * Determina as características de uma classe e carrega seus dados a partir de um `ReflectionClass`
 */
class MetaClass extends AbstractHasDocBlock
{

    /** @var ReflectionClass */
    protected $reflected;
    /** @var string */
    protected $namespace;
    /** @var string */
    protected $type;
    /** @var string */
    protected $name;
    /** @var MetaClass */
    protected $extends;
    /** @var ArrayIterator */
    protected $implements;
    /** @var ArrayIterator */
    protected $traits;
    /** @var ArrayIterator */
    protected $constants;
    /** @var ArrayIterator */
    protected $properties;
    /** @var ArrayIterator */
    protected $methods;
    /** @var ArrayIterator */
    protected $capabilities;

    public function __construct(ReflectionClass $class)
    {
        parent::__construct($class);
        $this->namespace = $class->getNamespaceName();
        $this->name = $class->getShortName();
        $this->loadType();
        $this->loadParent();
        $this->loadInterfaces();
        $this->loadTraits();
        $this->loadConstants();
        $this->loadProperties();
        $this->loadMethods();
        $this->loadResources();
    }



    private function loadType()
    {
        if ($this->reflected->isAbstract())
            $this->type = MetaClassType::T_ABSTRACT;
        else if ($this->reflected->isInterface())
            $this->type = MetaClassType::T_INTERFACE;
        else if ($this->reflected->isFinal())
            $this->type = MetaClassType::T_FINAL;
        else if ($this->reflected->isTrait())
            $this->type = MetaClassType::T_TRAIT;
        else
            $this->type = MetaClassType::T_REGULAR;
    }

    private function loadParent()
    {
        $parent = $this->reflected->getParentClass();
        if ($parent !== false)
            $this->extends = new MetaClass($parent);
    }

    private function loadInterfaces()
    {
        $this->implements = new ArrayIterator();
        foreach ($this->reflected->getInterfaces() as $interface) {
            $this->implements->append(new MetaClass($interface));
        }
    }

    private function loadTraits()
    {
        $this->traits = new ArrayIterator();
        foreach ($this->reflected->getTraits() as $trait) {
            $this->traits->append(new MetaClass($trait));
        }
    }

    private function loadConstants()
    {
        $this->constants = new ArrayIterator();
        foreach ($this->reflected->getConstants() as $name => $value) {
            $this->constants->append(new MetaConstant($name, $value));
        }
    }

    private function loadProperties()
    {
        $this->properties = new ArrayIterator();
        foreach ($this->reflected->getProperties() as $property) {
            if ($property->getDeclaringClass() == $this->reflected)
                $this->properties->append(new MetaProperty($property));
        }
    }

    private function loadMethods()
    {
        $this->methods = new ArrayIterator();
        foreach ($this->reflected->getMethods() as $method) {
            if ($method->getDeclaringClass() == $this->reflected)
                $this->methods->append(new MetaMethod($method));
        }
    }

    private function loadResources()
    {
        $this->capabilities = new ArrayIterator();
        if ($this->reflected->isAnonymous()) {
            $this->capabilities->append(MetaClassCapabilities::T_ANONYMOUS);
        }
        if ($this->reflected->isCloneable()) {
            $this->capabilities->append(MetaClassCapabilities::T_CLONEABLE);
        }
        if ($this->reflected->isInstantiable()) {
            $this->capabilities->append(MetaClassCapabilities::T_INSTANTIABLE);
        }
        if ($this->reflected->isInternal()) {
            $this->capabilities->append(MetaClassCapabilities::T_INTERNAL);
        }
        if ($this->reflected->isIterable()) {
            $this->capabilities->append(MetaClassCapabilities::T_ITERABLE);
        }
    }

    /**
     * Get the value of namespace
     *
     * @return  string
     */
    public function getNamespace(): string
    {
        return $this->namespace;
    }

    /**
     * Get the value of type
     *
     * @return  string
     */
    public function getType(): string
    {
        return $this->type;
    }

    /**
     * Get the value of name
     *
     * @return  string
     */
    public function getName(): string
    {
        return $this->name;
    }

    public function getNameClear(): string
    {
        return str_replace('_', '', $this->name);
    }

    /**
     * Get the value of extends
     *
     * @return  MetaClass
     */
    public function getExtends(): ?MetaClass
    {
        return $this->extends;
    }

    /**
     * Get the value of implements
     *
     * @return  MetaClass[]
     */
    public function getImplements(): ArrayIterator
    {
        return $this->implements;
    }

    /**
     * Get the value of traits
     *
     * @return  MetaClass[]
     */
    public function getTraits(): ArrayIterator
    {
        return $this->traits;
    }

    /**
     * Get the value of constants
     *
     * @return  MetaConstant[]
     */
    public function getConstants(): ArrayIterator
    {
        return $this->constants;
    }

    /**
     * Get the value of properties
     *
     * @return  MetaProperty[]
     */
    public function getProperties(): ArrayIterator
    {
        return $this->properties;
    }

    /**
     * Get the value of methods
     *
     * @return  MetaMethod[]
     */
    public function getMethods(): ArrayIterator
    {
        return $this->methods;
    }

    /**
     * Get the value of capabilities
     *
     * @return  string[]
     */
    public function getCapabilities(): ArrayIterator
    {
        return $this->capabilities;
    }
}

Resources/views/classes.tex.twig
{% autoescape "latex" %}
	\begin{tiny}    
						    \begin{landscape}
	{% for class in classes %}
		\clearpage
												        \begin{longtable}{|p{.2\linewidth}|p{.2\linewidth}|p{.5\linewidth}|}						
												            \hline
												            \multicolumn{3}{|p{.9\linewidth}|}{\textbf{Classe:}
		{{ class.type }}
		{{ class.name }}\label{tab:classe-{{ class.nameClear }}}
		{% if class.description %}\newline
			{{ class.description }}
		{% endif %}
		} \\
												            \multicolumn{3}{|l|}{\textbf{Namespace:}
		{{ class.namespace }}} \\\hline
		{% if not class.extends is null %}
			\multicolumn{3}{|l|}{\textbf{Herança de:} \hyperref[tab:classe-{{class.extends.nameClear}}]{
			{{ class.extends.namespace }}$\backslash${{class.extends.name}}
			} } \\\hline
		{% endif %}
		{% if class.implements.count > 0 %}
			\multicolumn{3}{|p{.9\linewidth}|}{\textbf{Implementa:}
			{% for interface in class.implements %}\hyperref[tab:classe-{{interface.nameClear}}]{~{{interface.namespace}}$\backslash${{interface.name}}}{% if not loop.last %},	{% endif %}{% endfor %}
			} \\\hline
		{% endif %}
		{% if class.traits.count > 0 %}
			\multicolumn{3}{|l|}{\textbf{Usa:}
			{% for trait in class.traits %}
				\hyperref[tab:classe-{{trait.nameClear}}]{
				{{trait.name}}
				}
				{% if not loop.last %},
				{% endif %}
			{% endfor %}
			} \\\hline
		{% endif %}
		{% if class.capabilities.count > 0 %}
			\multicolumn{3}{|l|}{\textbf{Capacidades:}
			{{ class.capabilities|join(', ') }}
			} \\\hline
		{% endif %}
		{% for tag in class.tags %}
            {% if not tag.name matches '/^@ORM.+$/' %}            
			    \multicolumn{3}{|l|}{\textbf{@{{tag.name}}} {{tag}}} \\\hline
            {% endif %}
        {% endfor %}
        {% for doc in class.doctrineAnnotations %}
			\multicolumn{3}{|l|}{\textbf{@{{doc.name}}} {{doc.value}}} \\\hline
        {% endfor %}
            {% if class.constants.count > 0 %}            
            \multicolumn{3}{|c|}{\textbf{Constantes}} \\\hline			            
            \textbf{Nome} & \textbf{Tipo} & \textbf{Valor} \\\hline
            {% for constant in class.constants %}
                {{ constant.name }} & {{ constant.type }} & {{ constant.value }} \\\hline
            {% endfor %} 
            {% endif %}    
            {% if class.properties.count > 0 %}                   
            \multicolumn{3}{|c|}{\textbf{Propriedades}} \\\hline
            {% for property in class.properties %}
            {{ property.isStatic ? 'static ' ~ property.name : property.name }}
                                {% if property.description %}                                
                                & \multicolumn{2}{p{.6\linewidth}|}{ {{ property.description }} } \\\cline{2-3}
                                {% endif %} 
                                & \multicolumn{2}{p{.6\linewidth}|}{\textbf{Visibilidade:}  {{property.visibility}} } \\\cline{2-3}
                                & \multicolumn{2}{p{.6\linewidth}|}{\textbf{Tipo:} {{ property.type ? property.type : 'Não definido' }} } \\\cline{2-3}
                                {% if property.defaultValue %}                                
                                & \multicolumn{2}{p{.6\linewidth}|}{\textbf{Valor inicial:} {{property.defaultValue}} } \\\cline{2-3}                                
                                {% endif %}                                
                                {% for tag in property.tags %}
                                {% if tag.name != 'var' and not tag.name matches '/^@ORM.+$/' %}                                                                    
                                & \multicolumn{2}{p{.6\linewidth}|}{\textbf{@{{tag.name}}} {{tag}}} \\\cline{2-3}                                        
                                {% endif %}
                                {% endfor %}
                                {% for doc in property.doctrineAnnotations %}                                
                                & \multicolumn{2}{p{.6\linewidth}|}{\textbf{@{{doc.name}}} {{doc.value}}} \\\cline{2-3}                                                                        
                                {% endfor %}
                                \hline                                
            {% endfor %}
            {% endif %}            
            {% if class.methods %}            
            \multicolumn{3}{|c|}{\textbf{Métodos}} \\\hline
            {% for method in class.methods %}
            {{ method.isStatic ? 'static ' ~ method.name : method.name }}
                            {% if method.description %}                            
                            & \multicolumn{2}{p{.6\linewidth}|}{ {{ method.description }} } \\\cline{2-3}
                            {% endif %} 
                            & \multicolumn{2}{p{.6\linewidth}|}{\textbf{visibilidade:} {{ method.visibility }} } \\\cline{2-3}							
                            & \multicolumn{2}{p{.6\linewidth}|}{\textbf{retorna:} {{ method.returnType ? method.returnType : 'Não definido' }} } \\\cline{2-3}
                            {% for tag in method.tags %}
                            {% if not tag.name in ['param', 'return'] and not tag.name matches '/^@ORM.+$/' %}                                                                    
                            & \multicolumn{2}{p{.6\linewidth}|}{\textbf{@{{tag.name}}} {{tag}}} \\\cline{2-3}                                        
                            {% endif %}
                            {% endfor %}
                            {% for doc in method.doctrineAnnotations %}                            
                            & \multicolumn{2}{p{.6\linewidth}|}{\textbf{@{{doc.name}}} {{doc.value}}} \\\cline{2-3}                                                                    
                            {% endfor %}
                            {% if method.parameters.count > 0 %}                                                        
                            & \multicolumn{2}{c|}{\textbf{Parâmetros}} \\\cline{2-3}
                            {% for param in method.parameters %}                                                            
                            & {{param.name}} &
                                        {% if param.description %}                                        
                                        {{param.description }} \\\cline{3-3} &&
                                        {% endif %} 
                                        \textbf{tipo:} {{param.type ? param.type : 'Não definido' }} 
                                        {% if param.defaultValue %}      
                                        \\\cline{3-3}                                  
                                        && \textbf{valor padrão:} {{param.defaultValue}} \\\cline{2-3}
                                        {% else %}
                                        \\\cline{2-3}
                                        {% endif %}
                            {% endfor %}                            
                            {% endif %}
                            \hline    
            {% endfor %}
            {% endif %}            	            																										
        \end{longtable}	
        {% endfor %}
    \end{landscape}		    
\end{tiny}
{% endautoescape %}

Resources/views/umlet.txt.twig
{% for class in classes %}
{% if class.type != 'class' %}<<{{class.type}}>>{% endif %}    
{{class.namespace}}::{{class.name}}
{% if class.constants.count > 0 %}
--
Constants
{% for constant in class.constants %}
{{constant.name}}: {{constant.type}} = {{constant.value}}
{% endfor %}
{% endif %}
{% if class.properties.count > 0 %}
--
{% for property in class.properties %}
{{ property.visibility == 'privado' ? '-' : property.visibility == 'público' ? '+' : '#' }}{{property.name}}: {{property.type}} {% if property.defaultValue %}= {{ property.defaultValue }}{% endif %}            
{% endfor %}
{% endif %}
{% if class.methods.count > 0 %}
--
{% for method in class.methods %}
{{ method.visibility == 'privado' ? '-' : method.visibility == 'público' ? '+' : '#' }}{{method.name}}({% for param in method.parameters %}{{param.name}}: {{param.type}}{% if param.defaultValue %} = {{param.defaultValue}}{% endif %}{% if not loop.last %}, {% endif %}{% endfor %}): {{method.returnType}}
{% endfor %}
{% endif %}    
{% endfor %}